### ISSUE TITLE
Zuuls "death" message should indicate that he's not dead.

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#123]
I encountered Zuul the gatekeeper after I killed him on an earlier floor.

**Comment by nikheizen** [comment]
This has always been the case.

https://github.com/martin-tornqvist/ia/blob/develop/src/properties.cpp#L1970
https://github.com/martin-tornqvist/ia/blob/develop/src/populate_monsters.cpp#L41

**Comment by martin-tornqvist** [comment]
Yes, as @nikheizen says, this is by design (although it did actually originate as a bug, but people thought it was a cool feature). I could have sworn though that Zuuls death message was changed to something more like "Zuul disappears!".

A minor hint is that Zuul does not leave a corpse:
https://github.com/martin-tornqvist/ia/blob/develop/src/actor_data.cpp#L1157

I'll change this issue for having a clearer death message for Zuul.

**Comment by hubertig** [comment]
Hi, I checked the code: "Zuul vanishes"
I didnt pay attention to it when playing. I just thought he's a unique so re-spawning is a bug.

**Comment by martin-tornqvist** [comment]
Oh, yeah you're right. The death message is overridden in the header file. Well then... I'm fine with the way things are :)
