### ISSUE TITLE
Suggestion: Explosion should destroy corpses

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#131]
When I kill a Zombie with dynamite, it leaves a corpse and will rise again. I think that's somewhat odd.
Also, at least in 18.2 it was the case that braziers and similar things survived dynamite explosions.

**Comment by martin-tornqvist** [comment]
This is due to corpses being much tougher now, so the explosion doesn't do enough damage to destroy them completely.

I agree that it's odd  though (realistically speaking). I think the solution might be to add a secondary condition, to always destroy monsters if the damage is over a certain threshold, regardless of the actor's HP.

**Comment by martin-tornqvist** [comment]
New commit: 8745cd7cf458bae385fc76d35973d5ba688cdfe5

Now dynamite should normally prevent leaving corpses.
