### ISSUE TITLE
monolith and monster awareness

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#150]
Not sure if cases such as this one are intended:
i touch a monolith and it makes Keziah aware of me. We have not met and she is in an unexplored part of the map. i knew because she then summons stuff of course :)

not sure if only distance and not reachability is the intended factor for the awareness increase

**Comment by martin-tornqvist** [comment]
It's intentional, I wanted to spice things up a bit by making the Monolith a little dangerous, and not just simple XP buckets.

Earlier, the monolith sometimes summoned monsters around you, but that was too much. So this is like a milder version of that.

I'm considering adding a wider range of random effects (perhaps also positive effects) to make it less predictable.

I think there must be a message hinting that it alerts monsters, because now you have no idea that it's because you activated the Monolith that monsters suddenly come running.

Also, it probably shouldn't alert monsters across the whole map, only within a certain distance.

**Comment by martin-tornqvist** [comment]
They no longer alert monsters.
