### ISSUE TITLE
Integrate doding and etherealness into the normal hit chance calculations

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#157]

**Comment by martin-tornqvist** [comment]
I think the situation can be solved by integrating Ethereal hit chance penalty into the normal hit chance calculation, instead of having it as a independent random chance.

On that matter, dodging (from dexterity) should probably also be integrated into the normal calculation - it's currently also an independent random chance.

**Comment by hubertig** [comment]
yes, the dodging thing would be good too. also for melee although there is no aiming, perhaps via v.
by the way i never understood what the melee percentage in the @ screen is about.

**Comment by martin-tornqvist** [comment]
> although there is no aiming, perhaps via v.

Yes I think melee hit chance should be displayed via v, just like ranged attack (with a breakdown of each modifier).

> by the way i never understood what the melee percentage in the @ screen is about.

This is your "raw" (pure) melee skill, before weapon modifier (weapons add a modifier to this value such as +5% or -15%).

**Comment by martin-tornqvist** [comment]
Related: #143

**Comment by martin-tornqvist** [comment]
The "Combat skills" section of the character screen doesn't seem very useful actually. Especially not if detailed stats should be displayed when [v]iewing monsters.

**Comment by martin-tornqvist** [comment]
Fixed: 0ef139b6904982eece76f04bc6b97d7a5dbe972e
