### ISSUE TITLE
Make Greater Polyps Greater

### ISSUE THREAD

**Issue by martin-tornqvist** [martin-tornqvist/ia#161]
> I wish you increase Greater Polyp spawn rate to spice up things, because 90% of times you can never see him in the game. He must see invis too, and spawn from dlvl_last - 8.

**Comment by Spoony1992** [comment]
Check my balance suggestions in my latest video comment section. I write a lot about balancing changes that can be made with changing values. Also this comment have ideas pull that will greatly enhance experience. Maybe you will like some of this, and add them into Enhancement category?
 Offtop: I can't compile because I'm on Windows. Sorry, I cant find another place to communicate with you. You dont answer on my Reddit, Gmail or Youtube comments.

**Comment by martin-tornqvist** [comment]
Are you referring to these vidoes?:
https://www.youtube.com/watch?v=W0mtDGPKDMk
https://www.youtube.com/watch?v=kdWdBqqiARY

It seems like I'm missing something - I don't see any comments for those videos.

**Comment by martin-tornqvist** [comment]
Done: 7cba75461627d51a1ed0580bd7aeaa9561cc2e2d
