### ISSUE TITLE
Sometimes CURSED lasts forever

### ISSUE THREAD

**Issue by ethanfine** [martin-tornqvist/ia#171]
Sometimes the CURSED effect from a mummy does not have a duration, and lasts forever. I tested with the self aware trait. If this is intentional then its very punishing and unforgiving. A CURSED character is much weaker, especially if they want to cast spells.

**Comment by martin-tornqvist** [comment]
It's intentional. The capitalized spelling of "CURSED" is supposed to indicate a permanent status.

I agree that it's pretty harsh. But on the other hand, this only happens when the mummies melee attack you (I think?), and also there should be a very good chance that you have some way to bless yourself by the time you encounter mummies.

Perhaps being cursed should not give you a penalty to spell cost however? It could be enough if it only has miscellaneous minor effects. (Then being blessed should not give a bonus to spell cost either, so it's symmetric.)
