### ISSUE TITLE
Confirmation for new character trait

### ISSUE THREAD

**Issue by iamstevevan** [martin-tornqvist/ia#175]
Often when I am pounding away at zombies, I will make it to the next level.  When this happens, I am not fast enough to stop my fingers (W+Left) and end up picking 'W' char trait (Strong Spirit), then immediately returned to the fray, causing a possible fatal trait progression.  Can a confirmation be added so that I get a fair chance to pick a new trait?

**Comment by martin-tornqvist** [comment]
In the next version you do not get XP for killing monsters, so this exact situation will never occur then.

The moments where you might gain a new level are stuff like identifying an item, using some feature on the map, or going to the next dungeon level (you gain a bit of XP for that). It seems like in those situations there should be less chance of accidentally picking a trait, since then you're probably not spamming repeated commands Or what do you think?

I'm not completely against adding a confirmation question, but I try to keep things like that to a minimum. I'm not a big fan of "are you sure you want to do that?" questions ;-)

But I'll consider adding it.

**Comment by iamstevevan** [comment]
Wow, thats a big change and if the exact situation will never occur then
I'm satisfied.  Looking forward to another version of this AMAZING game!

**Comment by martin-tornqvist** [comment]
Alright, cool - and thanks! You can read the ongoing changelog here if you wanna check out some more upcoming changes:
https://github.com/martin-tornqvist/ia/blob/develop/res/release_history.txt
