### ISSUE TITLE
Weight of items

### ISSUE THREAD

**Issue by enormandeau** [martin-tornqvist/ia#193]
I did some research into the weight of the items in Infra Arcana. I think some of the item weights could be modified.

I saw that IA uses weight categories rather than actual weights in kilos. Would it be hard to change back to kilos? Otherwise, the weights suggested in the attached Excel file can be used as a reference.

[item_weights.xlsx](https://github.com/martin-tornqvist/ia/files/1405178/item_weights.xlsx)

**Comment by martin-tornqvist** [comment]
I think using kilograms would be harder to manage, since I'd have to put realistic weights for stuff. I don't know exactly how much a Tommy Gun weights - it's easier to say that it's roughly the equivalent of an ax for example.

There is support for fine tuning the weights though. The weight categories just represents different values of weight units, but there's no problem with having an item weighing e.g. "medium + 20" units.

```
enum ItemWeight
{
    none        = 0,
    extra_light = 1,    // E.g. ammo
    light       = 10,   // E.g. dynamite, daggers
    medium      = 50,   // E.g. most firearms
    heavy       = 100,  // E.g. heavy armor, heavy weapons
};
```

**Comment by enormandeau** [comment]
Do you think if I give you a conversion from kilos to `units` it could do?

**Comment by enormandeau** [comment]
I think it would be feasible to convert units to kilograms and thus find how much a person can carry. I could then adjust the weights in units and make sure there is a global equivalence while tweaking some items that seemed off in the scale.

**Comment by martin-tornqvist** [comment]
Issue imported to GitLab
