### ISSUE TITLE
Rat-thing description

### ISSUE THREAD

**Issue by Kzer-Za** [martin-tornqvist/ia#207]
>their human hands and evil caricatures of human heads reveal their unnatural nature.

"unnatural nature" sounds a bit strange :) It may need some adjustment, if I may make a suggestion.

**Comment by martin-tornqvist** [comment]
Indeed! This has already been updated - many monster descriptions have been rewritten :)

>A malformed cross of rat and man, birthed from witchcraft. It has a warped human face and vestigial hands for forepaws.

A lot has actually happened since v19.2 - I recommend playing the automated builds, based on the master branch, which I talk about on the game's webpage (under "Latest builds"):

https://sites.google.com/site/infraarcana/
