### ISSUE TITLE
Some mixed bugs

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#99]
Hi,
I hope it's fine to report bugs here. If not let me know.
BTW this and the other issues I reported concern V18 (master).

- The timer turns green for free actions; it stays green if I wait (i.e., "5"); also it wont turn green if just waiting.
- I play Ascii and medical bags and mud are very similar if not even the same symbol+color, also I feel it'd be better if tombs were not "&" like corpses imo
- Rogue, Occultist, and Veteran start with +5% insanity; I.e. veteran gets a total of 15%. Nevermind, realized it's the latern.
- a potion of insight id-ed an amulet which was previously id-ed by behavior (it's the one that turns monsters against each other)

I really love the game, amazing work, thanks a lot for it!

**Comment by hubertig** [comment]
One more thing:

- Rogue, Occultist, and Veteran start with +5% insanity; I.e. veteran gets a total of 15%

**Comment by martin-tornqvist** [comment]
Hey,
It's absolutely fine! I appreciate it very much! Although lumping different issues together like this is probably not a good idea, since It makes it harder to close the issue.

I merged the develop branch into master right now btw (it was long overdue) - should be quite a lot of new stuff if you play on master.

* Yeah this is how it works. It's literally like the description says "every Nth step is a free action". The game counts the steps you take, and every Nth step is free. If you wait, shoot, kick, or do anything other than taking a step, your "step count" will stay the same. So that's why you can wait with a green counter for several turns - the next step is still the one that will be free. Now if this is a good design or not is debatable I guess, but it's totally intended. One advantage is that you don't have to fear losing free steps by e.g. waiting or attacking on the wrong turn. On the downside, it's a little bit weird that you can wait around with a free step "saved" that you're ready to use when you move.
* They are not **exactly** the same, but probably too close yes. I wonder what would be a better color. Light red? What symbol do you propose for tombs?
* Oh wow, I had to read your comment several times. The lantern causes insanity!! Haha this is not intended at all. I see now that it's because the lantern sets its data with "device" as item type base. So for the lantern I need to actively disable insanity. Really glad you brought my attention to this :D
* Are you sure it wasn't a separate effect on the amulet that was id-ed? Amulets can have multiple effects.

**Comment by martin-tornqvist** [comment]
Lantern bug fixed by cd3c054ca17f79806bb82ff5c0b3f67d112ba6e6

**Comment by hubertig** [comment]
Hi,
ok, I will report future issues separately.
Yes, the amulet had only one effect, which was id-ed twice. perhaps the gain in insight was that there are no other effects ?! I'd have preferred the potion id-ing my strange device though :)

Not sure, but lanterns, mud/water, devices, and medical bags would ideally have different symbols imo. maybe I'll get to think about good symbols later.

corpse: &
tomb: ß perhaps?

Thanks for replying! And thanks again for the game, it's my current favorite RL. I think it's quite hard to come up with new, good, and interesting RLs, so congrats on that :)

**Comment by martin-tornqvist** [comment]
Concerning identifying amulets; From reading the code, and doing some testing I recall now that this behavior is intended. Amulets may have one or two effects. If they only have one, knowledge of this requires magical identification. Sure, maybe it would be more valuable to identify something else like a device - but at least you now know there's no horrible hidden effect that will bite you at the worst possible time.

I will keep this behavior as it is, unless there's a massive uproar against it :P

**Comment by martin-tornqvist** [comment]
Ok so I've moved around the ASCII symbols a bit. The following updates have been made:
```
Tombs/gravestones changed from "&" to "]"
Fountains changed from "%" to "1"
Melee weapons changed from "(" to ")"
Misc tools and devices changed from "~"/"-" to "%" (explosives still use "-")
```

Updated in fd56c2934f297978416a200ed625c0b08576e3bf

**Comment by martin-tornqvist** [comment]
Ok, so it seems everything here has been accounted for - I'm closing it. You're welcome to open new issues if there's more problems with ascii symbols or anything.
